CREATE DATABASE IF NOT EXISTS Clinica_Veterinaria_CBA;
USE Clinica_Veterinaria_CBA;

-- Creaccion tabla Propietario
CREATE TABLE IF NOT EXISTS T_PROPIETARIO(
DNI CHAR(9) NOT NULL,
Nombre VARCHAR(10) NOT NULL,
Apellidos VARCHAR(15),
Direccion VARCHAR(30),
PRIMARY KEY (DNI)
);

-- Creaccion tabla Telefono Propietario
CREATE TABLE IF NOT EXISTS T_TELEFONO_PROPIETARIO(
DNI_propietario CHAR(9) NOT NULL,
Telefono INT(9),
PRIMARY KEY (DNI_propietario, Telefono),
CONSTRAINT FK_TELEFONO_PROPIETARIO
FOREIGN KEY (DNI_propietario) REFERENCES T_PROPIETARIO (DNI)
);

-- Creaccion tabla Contacto
CREATE TABLE IF NOT EXISTS T_CONTACTO(
DNI CHAR(9) NOT NULL,
Nombre VARCHAR(10) NOT NULL,
Tipo VARCHAR(15) NOT NULL,
DNI_propietario CHAR(9) NOT NULL,
PRIMARY KEY (DNI),
CONSTRAINT UK_CONTACTO_PROPIETARIO
UNIQUE (DNI_propietario),
CONSTRAINT FK_CONTACTO_PROPIETARIO
FOREIGN KEY(DNI_propietario) REFERENCES T_PROPIETARIO(DNI)
);

-- Creaccion tabla Mascota
CREATE TABLE IF NOT EXISTS T_MASCOTA(
Identificador INT NOT NULL,
Nombre VARCHAR(10) NOT NULL,
Tipo ENUM("Perro","Gato","Roedor","Ave","Reptil","Mamífero") NOT NULL,
Fecha_Nacimiento DATE,
DNI_propietario CHAR(9) NOT NULL,
PRIMARY KEY(Identificador),
CONSTRAINT FK_MASCOTA_PROPIETARIO
FOREIGN KEY (DNI_propietario) REFERENCES T_PROPIETARIO(DNI)
);

-- Creaccion tabla personal
CREATE TABLE IF NOT EXISTS T_PERSONAL(
Codigo CHAR(7) NOT NULL,
DNI CHAR(9) NOT NULL,
Nombre VARCHAR(10) NOT NULL,
Apellido1 VARCHAR(10) NOT NULL,
Apellido2 VARCHAR(10) NULL,
Telefono INT(9),
PRIMARY KEY(Codigo),
CONSTRAINT UK_PERSONAL
UNIQUE(DNI)
);

-- Creaccion tabla Veterinario
CREATE TABLE IF NOT EXISTS T_VETERINARIO(
Codigo CHAR(7) NOT NULL,
Especialidad VARCHAR(15) NOT NULL,
PRIMARY KEY(Codigo),
CONSTRAINT FK_VETERINARIO_PERSONAL
FOREIGN KEY(Codigo) REFERENCES T_PERSONAL(Codigo)
);

-- Creaccion tabla Mascota-Veterinario
CREATE TABLE IF NOT EXISTS T_MASCOTA_VETERINARIO(
ID_mascota INT NOT NULL,
Cod_veterinario CHAR(7) NOT NULL,
Fecha DATE NOT NULL,
Diagnostico VARCHAR(50),
PRIMARY KEY(ID_mascota, Cod_veterinario, Fecha),
CONSTRAINT FK_MASCTVETER_MASCOTA
FOREIGN KEY(ID_mascota) REFERENCES T_MASCOTA(Identificador),
CONSTRAINT FK_MASCTVETER_VETERINARIO
FOREIGN KEY(Cod_veterinario) REFERENCES T_VETERINARIO(Codigo)
);

-- Creaccion tabla Otros
CREATE TABLE IF NOT EXISTS T_OTROS(
Codigo CHAR(7) NOT NULL,
PRIMARY KEY(Codigo),
CONSTRAINT FK_OTROS_PERSONAL
FOREIGN KEY(Codigo) REFERENCES T_PERSONAL(Codigo)
);

-- Creaccion tabla Auxiliar
CREATE TABLE IF NOT EXISTS T_AUXILIAR(
Codigo CHAR(7) NOT NULL,
Fecha_alta DATE NOT NULL,
Base_cotizacion VARCHAR(30) NOT NULL,
PRIMARY KEY(Codigo),
CONSTRAINT FK_AUXILIAR_PERSONAL
FOREIGN KEY(Codigo) REFERENCES T_PERSONAL(Codigo)
);
