CREATE DATABASE IF NOT EXISTS Companya_Aerea_CBA;
USE Companya_Aerea_CBA;

-- TABLA AVION
CREATE TABLE IF NOT EXISTS T_AVION(
Matricula VARCHAR(7) NOT NULL,
Fabricante VARCHAR(30) NOT NULL,
Modelo VARCHAR(20),
Capacidad INT,
Autonomia INT,
PRIMARY KEY (Matricula)
)

-- TABLA VUELO
CREATE TABLE IF NOT EXISTS T_VUELO(
Identificador INT NOT NULL,
Fecha DATE,
Aeropuerto_origen VARCHAR(20),
Aeropuerto_destino VARCHAR(20),
Matricula_avion VARCHAR(7) NOT NULL,
PRIMARY KEY (Identificador),
CONSTRAINT FK_VUELO_AVION
FOREIGN KEY (Matricula_avion) REFERENCES T_AVION (Matricula)
)

-- TABLA PASAJERO
CREATE TABLE IF NOT EXISTS T_PASAJERO(
DNI VARCHAR(10) NOT NULL,
Nombre VARCHAR(20) NOT NULL,
PRIMARY KEY (DNI)
)

-- TABLA PASAJERO-VUELO
CREATE TABLE IF NOT EXISTS T_PASAJERO_VUELO(
ID_vuelo INT NOT NULL,
DNI_pasajero VARCHAR(10) NOT NULL,
Numero_asiento INT,
Clase ENUM("turista","primera","business"),
PRIMARY KEY (ID_vuelo, DNI_pasajero),
CONSTRAINT FK_PASAJ_VUELO
FOREIGN KEY (ID_vuelo) REFERENCES T_VUELO (Identificador),
CONSTRAINT FK_VUELO_PASAJERO
FOREIGN KEY (DNI_pasajero) REFERENCES T_PASAJERO (DNI)
)

-- TABLA PERSONAL
CREATE TABLE IF NOT EXISTS T_PERSONAL(
Identificador INT NOT NULL,
Nombre VARCHAR(20) NOT NULL,
Categoria_profesional VARCHAR(15),
PRIMARY KEY (Identificador)
)

-- TABLA PERSONAL-VUELO
CREATE TABLE IF NOT EXISTS T_PERSONAL_VUELO(
ID_vuelo INT NOT NULL,
ID_personal INT NOT NULL,
Puesto VARCHAR(15),
PRIMARY KEY (ID_vuelo, ID_personal),
CONSTRAINT FK_PERSO_VUELO
FOREIGN KEY (ID_vuelo) REFERENCES T_VUELO (Identificador),
CONSTRAINT FK_VUELO_PERSON
FOREIGN KEY (ID_personal) REFERENCES T_PERSONAL (Identificador)
)