CREATE DATABASE IF NOT EXISTS Empresa_CBA;
USE Empresa_CBA;

/*Creo tabla Cliente*/
CREATE TABLE IF NOT EXISTS T_CLIENTE(
DNI VARCHAR(9) NOT NULL,
Nombre VARCHAR(15) NOT NULL,
Apellidos VARCHAR(20),
Direccion VARCHAR(40) NOT NULL,
Telefono INT(9) NOT NULL,
PRIMARY KEY(DNI)
);

/*Creacion tabla Producto*/
CREATE TABLE IF NOT EXISTS T_PRODUCTO(
Codigo INT(5) NOT NULL,
Nombre VARCHAR(25) NOT NULL,
Precio_unitario DECIMAL(5,2) NOT NULL,
PRIMARY KEY(Codigo)
);

/*Creacion tabla Proveedor*/
CREATE TABLE IF NOT EXISTS T_PROVEEDOR(
NIF INT(9) NOT NULL,
Nombre VARCHAR(50) NOT NULL,
Direccion VARCHAR(40) NOT NULL,
Codigo_producto INT(5),
PRIMARY KEY(NIF),
CONSTRAINT FK_PROVEEDOR_PRODUCTO
FOREIGN KEY (Codigo_producto)REFERENCES T_PRODUCTO(Codigo)
);

/*Creacion tabla Cliente_Producto*/
CREATE TABLE IF NOT EXISTS T_CLIENTE_PRODUCTO(
DNI_cliente VARCHAR(9) NOT NULL,
Codigo_producto INT(5),
PRIMARY KEY(DNI_cliente, Codigo_producto),
CONSTRAINT FK_DNI_CLIENTE
FOREIGN KEY (DNI_cliente) REFERENCES T_CLIENTE(DNI),
CONSTRAINT FK_CODIGO_PRODUCTO
FOREIGN KEY(Codigo_producto) REFERENCES T_PRODUCTO(Codigo)
);
